// Writes public/js/config.js from environment variables at build time.
// Supabase's anon key is safe to ship to the browser (it's the public,
// RLS-restricted key), but we still keep it out of source control and
// inject it per-environment (local / preview / production).
require("dotenv").config();

const fs = require("fs");
const path = require("path");

const SUPABASE_URL = process.env.SUPABASE_URL;
const SUPABASE_ANON_KEY = process.env.SUPABASE_ANON_KEY;

if (!SUPABASE_URL || !SUPABASE_ANON_KEY) {
  console.error(
    "Missing SUPABASE_URL and/or SUPABASE_ANON_KEY.\n" +
      "Set them in a local .env file (see .env.example) or in your Vercel project's " +
      "Environment Variables before building."
  );
  process.exit(1);
}

const outPath = path.join(__dirname, "..", "public", "js", "config.js");
const contents = `// Generated by scripts/generate-config.js at build time. Do not edit directly.
window.SUPABASE_CONFIG = {
  url: ${JSON.stringify(SUPABASE_URL)},
  anonKey: ${JSON.stringify(SUPABASE_ANON_KEY)},
};
`;

fs.mkdirSync(path.dirname(outPath), { recursive: true });
fs.writeFileSync(outPath, contents);
console.log(`Wrote ${outPath}`);
